In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

# Any results you write to the current directory are saved as output.

In [2]:
from keras.datasets import mnist

Using TensorFlow backend.


In [3]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [4]:
import matplotlib.pyplot as plt
for item in range(5):
    digit = train_images[item]
    plt.imshow(digit, cmap=plt.cm.binary)
    plt.show()

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

In [5]:
train_images.shape

(60000, 28, 28)

In [6]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [8]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(784, activation='relu'))
network.add(layers.Dense(16, activation='relu'))
network.add(layers.Dense(16, activation='relu'))
network.add(layers.Dense(10, activation='softmax'))

In [9]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [10]:
train_images = train_images.reshape((60000, 28 * 28))

In [11]:
train_images = train_images.astype('float32')/ 255

In [12]:
test_images = test_images.reshape(10000, 28 * 28)

In [13]:
test_images = test_images.astype('float32')/255

In [14]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [15]:
network.fit(train_images, train_labels, epochs=10, batch_size=128)

Epoch 1/10
60000/60000 [==============================] - 6s 97us/step - loss: 0.3269 - acc: 0.9031
Epoch 2/10
60000/60000 [==============================] - 6s 95us/step - loss: 0.1113 - acc: 0.9672
Epoch 3/10
60000/60000 [==============================] - 5s 90us/step - loss: 0.0714 - acc: 0.9786
Epoch 4/10
60000/60000 [==============================] - 6s 95us/step - loss: 0.0529 - acc: 0.9844
Epoch 5/10
60000/60000 [==============================] - 5s 91us/step - loss: 0.0395 - acc: 0.9878
Epoch 6/10
60000/60000 [==============================] - 6s 95us/step - loss: 0.0304 - acc: 0.9904
Epoch 7/10
60000/60000 [==============================] - 6s 95us/step - loss: 0.0242 - acc: 0.9925
Epoch 8/10
60000/60000 [==============================] - 6s 94us/step - loss: 0.0190 - acc: 0.9938
Epoch 9/10
60000/60000 [==============================] - 5s 90us/step - loss: 0.0151 - acc: 0.9952
Epoch 10/10
60000/60000 [==============================] - 6s 92us/step - loss: 0.0121 - acc: 0.9963

In [16]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('Test accuracy: ' + str(test_acc))

10000/10000 [==============================] - 1s 57us/step
Test accuracy: 0.975


In [17]:
# Create an HTML canvas to evaluate the model
from IPython.display import HTML
import cv2
import numpy as np
import base64

def classify(img):
    img = base64.b64decode(img[len('data:image/png;base64,'):])
    img = cv2.imdecode(np.fromstring(img, np.uint8),-1)
    img = cv2.resize(img[:,:,3], (28,28))
    img = img.reshape((1,784)).astype(np.float32)/255
    return network.predict_classes(img)[0]

HTML(filename = "mnist.html")

In [18]:
network.predict_proba(np.random.rand(1,784))

array([[1.01321398e-19, 9.72057700e-01, 2.79421676e-02, 2.39411735e-13,
        1.42360679e-24, 1.66869488e-16, 3.07397191e-10, 1.07352044e-07,
        1.05827825e-12, 0.00000000e+00]], dtype=float32)

In [19]:
network.predict_classes(test_images)

array([7, 2, 1, ..., 4, 5, 6])